version: "3.2"

services:
  family_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: Family-API
    image: family_api:${VERSION:-latest}
    volumes:
      - .:/app
    ports:
      - "8114:80"
    env_file:
      - .env
    networks:
      - family_net

  tg_mail:
    image: "catatnight/postfix"
    container_name: Family-Mailer
    environment:
      - maildomain=${MAIL_DOMAIN}
      - smtp_user=${MAIL_USER}:${MAIL_PASSWORD}
    ports:
      - "25:25"
    restart: always
    networks:
      family_net:

networks:
  family_net:
