NONE = "none"
GUEST = "none"
READ = "access"
WRITE = "edit"
MODERATOR = "accept"
ADMIN = "admin"

NONE_LEVEL = 5
GUEST_LEVEL = 4
READ_LEVEL = 3
WRITE_LEVEL = 2
MODERATOR_LEVEL = 1
ADMIN_LEVEL = 0

ROLE_LEVEL_MAP = {
    ADMIN: ADMIN_LEVEL,
    MODERATOR: MODERATOR_LEVEL,
    WRITE: WRITE_LEVEL,
    READ: READ_LEVEL,
    GUEST: GUEST_LEVEL,
    NONE: NONE_LEVEL,
}
