NONE, NONE_LEVEL = "none", 4
READ, READ_LEVEL = "access", 3
WRITE, WRITE_LEVEL = "edit", 2
MODERATOR, MODERATOR_LEVEL = "accept", 1
ADMIN, ADMIN_LEVEL = "admin", 0


ROLE_LEVEL_MAP = {
    ADMIN: ADMIN_LEVEL,
    MODERATOR: MODERATOR_LEVEL,
    WRITE: WRITE_LEVEL,
    READ: READ_LEVEL,
    NONE: NONE_LEVEL,
}
